### ISSUE TITLE
another typo on readme ?

### ISSUE THREAD

**Issue by capito27** [delebile/arm9loaderhax#3]
"Inject sector.bin at sector 0.96, in the plaintext output you'll have."
shouldn't it be "...at sector 0**x**96..." ?

**Comment by capito27** [comment]
also, (although this has nothing to do with the readme), what would be the maximum size for both payload stages ?

**Comment by pixel-stuck** [comment]
@capito27 I'd guess max size of the payload would be firm0 size - firm1 size because firm0 is modified so when the smaller firm1 is loaded the payload is appended to the end... Unless you meant the payload loaded from SD? I'd imagine the payload size should have the same constraints as any normal Brahma payload, I may be wrong though...

**Comment by jasondellaluce** [comment]
This typo will be fixed asap.
The stage1 payload is stricted to size 0x1C00 in bytes, thata why stage2 actually exists.
That is useful just to read the sdcard payload, i've not planned any specific size for it, it is very small too.
I reserved it 0x20 sectors iirc.

**Comment by Syphurith** [comment]
@capito27 Well.. As of now maybe the README isn't more important than development.
BTW [Delebile Blog Article](http://delebile.bplaced.net/page.php?id&p=arm9loaderhax.html) could be better as the explanation.
@delebile Thanks for your effort! _It would be good to find out operations with GSP Reg in FIRM.._

**Comment by jasondellaluce** [comment]
That's someting i'll try to achieve too, thanks!
