### ISSUE TITLE
Building a payload with linux fails to work properly

### ISSUE THREAD

**Issue by pixel-stuck** [delebile/arm9loaderhax#4]
When built with linux the installer payload gets stuck at "Exploiting arm9..." and if you use an installer made by someone else you'll get a brick... after using the installer made by someone else if you use a NAND mod to flash sector 0x96 manually makes the hax behave normally and payloads that are built for it work fine

**Comment by jasondellaluce** [comment]
Then it surely is a Linux building issue, i'll have to look for the problem...
I'll probably need some help, since right now i only have access to windows PCs at home.

**Comment by pixel-stuck** [comment]
We're messing with it on IRC right now... I'll probably fix it and make a pull request

**Comment by jasondellaluce** [comment]
The way you described it made me suppose that both the sector and the payloads work fine, the only issue is in the installer arm9 code.

**Comment by gemarcano** [comment]
Eh, it's a little more complicated than that. dark-samus used a 3dsx file from another user, and since the payloads and stuff is loaded onto the .3dsx, it makes sense his sector.bin would be wrong, and thus flashing it again would fix it.

That having been said, users compiling on Linux, like myself, would get firm0.bin, firm1.bin, and the stage*.bin be different than when compiled in Windows. That seems like the real issue with Linux/Windows. This difference seems crucial, since it bricked me (I had hardmod so I could recover). Compiling with Windows made arm9launcherhax work for me.

**Comment by jasondellaluce** [comment]
That still is an issue in the compilation of arm9 code

**Comment by gemarcano** [comment]
Pull request #6 fixes the Linux issue. I've tested it, and it works. I've also checked the resulting binaries along with b1l1s's help, and they now have jumps after the nop slide, unlike before.

**Comment by jasondellaluce** [comment]
Merged!

**Comment by pixel-stuck** [comment]
I can confirm this fixes the issue, closed
